language: java
jdk:
- openjdk8
before_install:
  - echo "Setting project environment variable."
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
after_success:
  - wget https://www.doggycraft.dk/travis/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://www.doggycraft.dk/travis/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
addons:
  sonarcloud:
    organization: "doggycraftdk"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DoggyCraftDK_SeriousBusiness