language: java
jdk:
- openjdk8
after_success:
  - wget https://www.doggycraft.dk/travis/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://www.doggycraft.dk/travis/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
addons:
  sonarcloud:
    organization: "doggycraftdk"
    token:
      secure: $SONAR_TOKEN

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=DoggyCraftDK_SeriousBusiness