name: SeriousBusiness
author: DogOnFire
version: ${project.version}
api-version: 1.14
website: "http://dev.bukkit.org/server-mods/seriousbusiness"
main: com.dogonfire.seriousbusiness.Company
softdepend: 
  - WorldGuard
  - Vault
commands:
  business:
    description: "Controls the Serious Business system"
    usage: /business
permissions: 
  company.*: 
    children: 
      business.listen: true
      business.followers: true
      business.help: true
      business.home: true
      business.info: true
      business.list: true
      business.ceo: true
      business.ceo.invite: true
      business.ceo.description: true
      business.ceo.fire: true
      business.reload: true
      business.sethome: true
    default: false
    description: "Gives access to all Serious Business commands"
  business.pray: 
    default: true
    description: "Player can pray directly to their Gods using /g prayfor command"
  business.listen: 
    default: true
    description: "Player can hear Gods speaking"
  business.updates: 
    default: false
    description: "Player gets notifications about updates to Gods plugin"
  business.love: 
    default: true
    description: "Allows the Player to love his partner"