name: SeriousBusiness
author: DogOnFire
version: ${project.version}
api-version: 1.14
website: "http://dev.bukkit.org/server-mods/seriousbusiness"
main: com.dogonfire.seriousbusiness.Company
softdepend: 
  - WorldGuard
  - Vault
commands:
  company:
    description: "Controls the Serious Business companies"
    usage: /company
  patent:
    description: "Controls the Serious Business patents"
    usage: /patent
  job:
    description: "Controls the Serious Business jobs"
    usage: /job
  jobs:
    description: "Controls the Serious Business jobs"
    usage: /job
  land:
    description: "Controls the Serious Business lands"
    usage: /land
  tax:
    description: "Controls the Serious Business tax system"
    usage: /tax
  shop:
    description: "Controls the Serious Business shopping system"
    usage: /shop
  shops:
    description: "Controls the Serious Business shopping system"
    usage: /shop
  stocks:
    description: "Controls the Serious Business stocks system"
    usage: /stocks
permissions: 
  company.*: 
    children: 
      company.listen: true
      company.help: true
      company.company.help: true
      company.shop.help: true
      company.job.help: true
      company.land.help: true
      company.sethome: true
      company.fire: true
      company.home.hq: true
      company.home.shop: true
      company.info: true
      company.list: true
      company.land: true
      company.ceo: true
      company.ceo.invite: true
      company.ceo.description: true
      company.ceo.fire: true
      company.reload: false
      company.sellsign.build: true
      company.shop: true
      company.shop.goto: true
      company.shop.search: true
      company.trade: true
      company.invite: true
      company.workas: false
      company.quit: true
      company.deposit: true
      company.withdraw: true
      company.setwage.production: true      
      company.setwage.manager: true      
      company.setwage.sales: true      
      job: true
      job.search: true
      job.apply.goto: true
      patent: true
      patent.apply: true
      patent.list: true
      stocks: true
      stocks.buy: true
      stocks.sell: true
      land.land: true
      shop: true
      shop.search: true
      shop.goto: true
    default: false
    description: "Gives access to all Serious Business commands"
  company.listen: 
    default: true
    description: "Player gets information about his Company"
  company.updates: 
    default: false
    description: "Player gets notifications about updates to Company plugin"