name: SeriousBusiness
author: DogOnFire
version: ${project.version}
api-version: 1.14
website: "http://dev.bukkit.org/server-mods/seriousbusiness"
main: com.dogonfire.seriousbusiness.Company
softdepend: 
  - WorldGuard
  - Vault
commands:
  company:
    description: "Controls the Serious Business companies"
    usage: /company
  tax:
    description: "Controls the Serious Business tax system"
    usage: /tax
permissions: 
  company.*: 
    children: 
      company.listen: true
      company.followers: true
      company.help: true
      company.home.hq: true
      company.home.sales: true
      company.info: true
      company.list: true
      company.land: true
      company.ceo: true
      company.ceo.invite: true
      company.ceo.description: true
      company.ceo.fire: true
      company.reload: true
      company.sethome: true
    default: false
    description: "Gives access to all Serious Business commands"
  company.listen: 
    default: true
    description: "Player gets information about his Company"
  company.updates: 
    default: false
    description: "Player gets notifications about updates to Company plugin"